MY_COMPONENT_PATH := $(shell component-tool localpath --repo=qemu --type=$(BUILD_TYPE) qemu)
QEMU_TOP := $(WORKSPACE_TOP)/qemu

build:
	echo "start build qemu"
	mkdir -p $(MY_COMPONENT_PATH)/qemu_deb_files/
	cp -r $(QEMU_TOP) $(MY_COMPONENT_PATH)/qemu_deb_files/ || true
	cd $(MY_COMPONENT_PATH)/qemu_deb_files/qemu
	dpkg-buildpackage -rfakeroot -uc -b

clean:
	sudo rm -rf $(MY_COMPONENT_PATH)
docker:
	
