MY_COMPONENT_PATH := $(shell component-tool localpath --repo=qemu --type=$(BUILD_TYPE) qemu)
QEMU_TOP := $(WORKSPACE_TOP)/qemu

build:
	echo "start build qemu"
	mkdir -p $(MY_COMPONENT_PATH)/qemu_deb_files/
	cp -r $(QEMU_TOP) $(MY_COMPONENT_PATH)/qemu_deb_files/
	cd $(QEMU_TOP) $(MY_COMPONENT_PATH)/qemu_deb_files/qemu && exec dpkg-buildpackage -rfakeroot -uc -b

clean:
	sudo rm -rf $(MY_COMPONENT_PATH)
